// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Should not render <Observer /> render outside view 1`] = `
<Observer
  render={[Function]}
  tag="div"
  threshold={0}
  triggerOnce={false}
>
  <div>
    Inview: 
    false
  </div>
</Observer>
`;

exports[`Should render <Observer /> render when in view 1`] = `
<Observer
  render={[Function]}
  tag="div"
  threshold={0}
  triggerOnce={false}
>
  <div>
    Inview: 
    true
  </div>
</Observer>
`;

exports[`Should render <Observer /> with children inview 1`] = `
<Observer
  className="observer"
  tag="div"
  threshold={0}
  triggerOnce={false}
>
  <div
    className="observer"
  >
    <div>
      Content
    </div>
  </div>
</Observer>
`;

exports[`Should render <Observer /> with children outside view 1`] = `
<Observer
  className="observer"
  tag="div"
  threshold={0}
  triggerOnce={false}
>
  <div
    className="observer"
  >
    <div>
      Content
    </div>
  </div>
</Observer>
`;

exports[`Should throw error when not passing ref 1`] = `"An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \\"Pause on exceptions\\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."`;
